### ISSUE TITLE
Bump requirements

### ISSUE THREAD

**Issue by vv12131415** [weirdan/codeception-psalm-module#13]
Can you please bump the requirements of this lib.

The easy one is 
```json
"composer/semver": "^1.4 || ^2.0 || ^3.0"
```

**Comment by weirdan** [comment]
Fixed in [0.7.3](https://github.com/weirdan/codeception-psalm-module/releases/tag/0.7.3).

**Comment by weirdan** [comment]
This actually broke builds in doctrine plugin when comparing dev versions.
