### ISSUE TITLE
Allow invoking psalm with xdebug enabled

### ISSUE THREAD

**Issue by mr-feek** [weirdan/codeception-psalm-module#17]
👋 
Idea: Allow invoking psalm with xdebug enabled so that we can debug codeception tests. This is very helpful for me while writing new functionality in the laravel plugin.

The `cmd` will need to be changed to something like `PSALM_ALLOW_XDEBUG=1 /usr/local/bin/php ' . $this->config['psalm_path']` ... This works for me locally, but I'm not sure if it will work cross platform, etc.

I think we will also need to set `vendor/vimeo/psalm/src/psalm.php` as the psalm path, instead of just `vendor/bin/psalm`

**Comment by weirdan** [comment]
> Idea: Allow invoking psalm with xdebug enabled so that we can debug codeception tests. This is very helpful for me while writing new functionality in the laravel plugin.

Have you tried running your test suite as `PSALM_ALLOW_XDEBUG=1 vendor/bin/codecept run`? Environment is inherited by child processes by default, so this variable should be available to Psalm as well.

> I think we will also need to set `vendor/vimeo/psalm/src/psalm.php` as the psalm path, instead of just `vendor/bin/psalm`

Why?

**Comment by mr-feek** [comment]
You know what, simply invoking `PSALM_ALLOW_XDEBUG=1 vendor/bin/codecept run` seems to work fine for me now. I think I went too far down the rabbit hole trying to figure out what was wrong before I found I needed `PSALM_ALLOW_XDEBUG=1` altogether.
