### ISSUE TITLE
[Enhancement] Allow asserting that psalm returned a certain exit code

### ISSUE THREAD

**Issue by mr-feek** [weirdan/codeception-psalm-module#9]
👋 This is very much an edge case that I am trying to test: https://github.com/psalm/psalm-plugin-laravel/pull/56 Essentially i want to expect psalm to fail, and assert that the status code is not 0.

We could accomplish this is by asserting a non-zero response code in `seeTheseErrors`. What do you think?

**Comment by weirdan** [comment]
Fixed in  3edfae6 (thanks!)
